# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNevegacioncompleja():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_nevegacioncompleja(self):
    # Test name: nevegacion-compleja
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://cursosdedesarrollo.com/")
    # 2 | click | css=.size-70 > .g-content | 
    self.driver.find_element(By.CSS_SELECTOR, ".size-70 > .g-content").click()
    # 3 | click | id=wp-block-search__input-1 | 
    self.driver.find_element(By.ID, "wp-block-search__input-1").click()
    # 4 | type | id=wp-block-search__input-1 | docker
    self.driver.find_element(By.ID, "wp-block-search__input-1").send_keys("docker")
    # 5 | click | css=.wp-block-search__button | 
    self.driver.find_element(By.CSS_SELECTOR, ".wp-block-search__button").click()
    # 6 | assertText | css=h1 | Search results for: docker
    assert self.driver.find_element(By.CSS_SELECTOR, "h1").text == "Search results for: docker"
    # 7 | open | /sorteo-pycones-2021/ | 
    self.driver.get("https://cursosdedesarrollo.com/sorteo-pycones-2021/")
    # 8 | assertText | css=.entry-title | Sorteo PyConEs 2021
    assert self.driver.find_element(By.CSS_SELECTOR, ".entry-title").text == "Sorteo PyConEs 2021"
  
